version: "3"

services:
  db:
    container_name: todoapp_next_express_db
    image: mysql:5.7
    environment:
      - TZ=Asia/Tokyo
      - 'MYSQL_ROOT_PASSWORD=password'
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
    networks:
      - default
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: "yarn dev"
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/app
    tty: true

  api:
    build:
      context: .
      dockerfile:  Dockerfile.api
    command: "yarn start"
    ports: 
      - "9999:9999"
    volumes:
      - ./api:/app