FROM node:14.15.4-alpine3.12

WORKDIR /app

RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache git

COPY api/package.json .
COPY api/yarn.lock .
RUN yarn install

COPY ./api .

EXPOSE 9999

CMD yarn dev