FROM node:14.15.4-alpine3.12

WORKDIR /app

RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache git

COPY frontend/package.json .
COPY frontend/yarn.lock .
RUN yarn install

COPY ./frontend .

EXPOSE 3000

CMD yarn start